### PR TITLE
Implement OAuth2 token exchange

### PR DESCRIPTION
**Pull request by jhoerr**
IT People API is responsible for exchanging an OAuth token code from the frontend for a UAA JWT. This branch implements that feature. 

This PR got kinda big.... It also:
* Added some TeamCity assets to help get the API docker image built and pushed to UITS docker
* Fixes a few OAuth related issues that emerged on testing after we got up and running in Docker
* Adds a Postgres Script that will prep the DBA Postgres database to accept EntityFamework migrations.

### CODE REVIEW

**Review by vbhupathi — APPROVED** [review]
OAuth stuff always scares me but this looks great!

**Comment by jhoerr** [comment]
@vbhupathi I hear that! It's painful partly because OAuth is painful, and partly because of some implementation choices they made for UAA. We can deep dive on it sometime if you want.

**Comment by vbhupathi** [comment]
> @vbhupathi I hear that! It's painful partly because OAuth is painful, and partly because of some implementation choices they made for UAA. We can deep dive on it sometime if you want.

Sure, @jhoerr will do that, thanks!

**Review by jasonfrancis — APPROVED** [review]
This looks good.  It's great to have the migrations, oauth2, and CORS hurdles cleared.

**Review by sgarneni — APPROVED** [review]
**Nice work!**

**Pull request merged**
