### PR TITLE
Support types

### PR DESCRIPTION
**Pull request by jardrake**
As a Unit Manager I'd like to define the type of support our unit provides to a department

When adding a departmental support relationship, choose from the following support type options:
- Full Service
- Desktop/Endpoint
- Web/app Infrastructure
- Research Infrastructure

### CODE REVIEW

**Review by jasonfrancis — APPROVED** [review]
Possibly `SupportType.Name` should have a unique constraint, but since only devs can add/remove them by tickling the database it should not be a problem.

Love the default values baked right into to the migration and updated OpenAPI documentation.

**Review by vbhupathi — APPROVED** [review]

**Review by jasonfrancis — APPROVED** [review]
Good to have the migration preventing duplicates

**Comment by jasonfrancis** [comment]
I stand by my review after that last commit.

**Comment by vbhupathi** [comment]
It looks good to go 👍

**Pull request merged**
