### PR TITLE
Support reporting

### PR DESCRIPTION
**Pull request by jasonfrancis**
# Purpose
Management would like to have 1:1 reports that show "this department is supported by this unit." This was not practical because `Departments` have a 1:many relationship with `Units` through `SupportRelationships` .

# Overview
Adds a `ReportSupportingUnit` property to the `Department` class. This sounds trivial, and that part was; but we need to assure that the value is always correct.  That means we needed to carefully constrain the possible values to just `Units` (and their parentage) that have `SupportRelationships` with that `Department`. We also must tightly control who can set the value.

### Case 1
When a `Unit's` owner creates a new `SupportRelationship` for a `Department` that does not yet have a `ReportSupportingUnit` they are prompted to pick one from a list of their `Unit` and its parents.  They must pick a value to create the `SupportRelationship`.

image

### Case 2
When a `Unit's` owner creates a new `SupportRelationship` for a `Department` that already has a `ReportSupportingUnit` they are also prompted to pick a value, but the existing value is selected by default.  If they want to change the value they are shown a warning message that their request will need to be reviewed and will not happen immediately.

image

If they have requested to change the `Department's` `ReportSupportingUnit` a `Notification` will be generated.  More on notifications below.

### Case 3
When a `Unit's` owner deletes a `SupportRelationship` for a `Department` for their `Unit`, and the `Department's` current `ReportSupportingValue` becomes invalid it is set to `null`, and a Notification is created for the admins to review. More on notifications below.

### Case 4
When an admin creates a new `SupportRelationship` between a `Unit` and a `Department` they are prompted to to pick a `ReportSupportingUnit`, but they have more options and can pick any `Unit` (or its parents) that has a `SupportRelationship` with the `Department`

### Case 5
When an admin views a `Department` that has `SupportRelationships` they are able set or update the `ReportSupportingUnit`.

> A Department with SupportRelationships to Units, but no ReportSupportingUnit set
> image

> A Department with multiple SupportRelationships to Units
> image

## Notifications
The new features result in workflows that require an IT People admin to decide which changes to allow or deny.  This is accomplished by `Notification` records.  `Notifications` show a message about the requested action, the time they were created, and if they have been reviewed yet.

When an admin logs in to IT People it will indicate the number of Notifications that need reviewed.

image

Following the "Notifications" link in the header will take to you to the Notifications list view.

image

Once an admin has taken whatever action is needed based on a `Notification` they should click the "Mark as Reviewed" button.  This will remove that `Notification` from the list of active `Notifications`.

`Notifications` that have already been reviewed can be seen by clicking the "Show Reviewed Notifications" button.

image

### CODE REVIEW

**Comment by jasonfrancis** [comment]
The pipeline is failing to deploy the Blazor project to blob storage

```
Batch upload assets from /opt/cssd/myagent/_work/2/Web/wwwroot to itpeopletestv2\$web
az storage blob upload-batch --source '/opt/cssd/myagent/_work/2/Web/wwwroot' --destination '$web' --account-name 'itpeopletestv2' --auth-mode login
ERROR: 
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
                    
##[error]Error uploading assets from /opt/cssd/myagent/_work/2/Web/wwwroot to itpeopletestv2\$web
##[error]Script failed with exit code: 1
```
My guess is that the Service Connection we had to recreate somehow had specific permissions on the IT People blob storage, will sift through permissions Monday morning.

**Comment by jasonfrancis** [comment]
Got some solid feedback that `Department.ReportSupportingUnit` would be better named `Department.PrimarySupportUnit`.  It's less of a mouthful and more intuitive for users.

**Review by bmoberly — APPROVED** [review]
I'm not as familiar with this project as I should be, but I'm not seeing anything that raises red flags.

**Review by vbhupathi — APPROVED** [review]
This looks great, Jason. However, based on how demanding these requests are, let's see how it turns out.

**Comment by jasonfrancis** [comment]
Taking this back to a draft, there are some reorganizations and realignments that need to settle down before we can consider proceeding with this work.

**Comment by jasonfrancis** [comment]
As a result of the re-orgs and key staff departures this is no longer a priority.  Closing PR.

**Pull request closed without merging**
