### PR TITLE
Unit Member Tools

### PR DESCRIPTION
**Pull request by jasonfrancis**
* Adds the remaining end points for managing Unit Member Tools.
* Adds Pact contract tests to ensure the results from the API are what the React front-end expects.
  * Involved adding a "State Server" docker container that is now used by both the integration tests and contract tests to reset the database.
* Responses have been refactored to use `ContentResult` for most responses
  * This was done because contract tests expected certain headers that could not be set with the other`IActionResults` we had been using.
* Standardized on one set of JSON serializer rules in `Models.Json.JsonSerializerSettings`.
* Adds some attributes to models to make sure the resulting JSON matches what is expected by the front-end.
* Adds missing includes.
* Improves tests to verify orphans aren't created in the database when relationships are broken/deleted.

### CODE REVIEW

**Review by jhoerr — APPROVED** [review]
Looks good to me!

**Review by vbhupathi — COMMENTED** [review]
Everything looks good, just a little concerned about `pact/StateServer/local.settings.json`  do you want to ignore it just in case if we forget in the future?

**Comment by jhoerr** [comment]
@vbhupathi Yeah -- thanks for noticing that. Please add `local.settings.json` to the `.gitignore.`

**Review by sgarneni — APPROVED** [review]
**Looks Good**

**Pull request merged**
